
    该例中，由于题目要求返回最大的值，肯定要建立一个循环逐个寻找。于是一个循
环框架在脑海中便形成了：

    int k;
    for(k=0; k<n; k++)  ...

    遇到寻找最大数的时候，通常要有一个变量来进行比较，在遇到比这个变量大的数
时，便再将这个数的值赋给这个变量。说到这里，读者也应该想到在最初应该把这个变
量在最初赋一个较小的值了，例如是零。若有负数的话，可以赋为0xffff等极小值。而
寻找最小数的时候呢？自然应该赋一个最大的值了。如0x8fff等。

    还有，在通过指针引用变量的时候，不要忘了加'*'号。否则变成引用地址了。读者
在自理指针问题的时候要格外小心，因为遇到指针误用、数组越界等问题时，通常会造
成死机或者更坏的后果。
