
    请编写函数fun，该函数的功能是：将Ｍ行Ｎ列的二维数组中的数据，按行的顺序依
次放到一维数组中，一维数组中数据的个数存放在形参b所指的存储单元中。

    例如，若二维数组中的数据为：

    33 33 33 33
    44 44 44 44
    55 55 55 55

    则一维数组中的内容应是：

    33 33 33 33 44 44 44 44 55 55 55 55

    注意：部分源程序给出如下：

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
