
    下列给定程序中，函数fun的功能是：首先把b所指字符串中的字符按逆序存放，然
后将a所指字符串中的字符和b所指字符串的字符，按排列的顺序交叉合并到c所指数组中
，过长的剩余字符接在c所指数组的尾部。例如，当a所指字符串中的内容为abcdefg，b
串中的内容为1234时，c所指数组中的内容应该为a4b3c2d1efg；而当a所指字符串中的内
容为1234，b所指字符串中的内容为abcdefg时，c所指数组中的内容应该为1g2f3e4dcba
。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main的函数，不得增行或删行，也不得更改程序的结构！
