在这个程序中，您可以发现几个比较隐蔽的错误：

１、将s[j++] = s[i]; 误写为：s[j] = s[i]; 由于是给字符串中的每个字符赋值，所
以必须有变量要指向字符串中的每一个字符，而这个变量则必须是递增或递减变化的，
否则无论执行多少遍，也只是给一个字符赋值而已。

２、将s[j] = '\0'; 误写为：s[j] = "\0";  单引号和双引号是不同的概念，前者表示
一个字符，这是字符串结束的标志；而后者则表示一个字符串，其第一个字符为'\0'，
即表示这是一个空字符串而已，当用printf函数显示时无内容。
