
    这个程序并不难，只是有的读者会将a[k]对应为a[L-k]，这是不正确的，不信您可
以代几个值来看一看。

    这个问题是本例的要点，还有要提醒您的是：对两个数的交换问题：也许有的读者
会写成：
        x = y;  y = x;

    其实这是达不到目的的，程序执行第一条语句的时候，会把x原有的值覆盖掉，于是
x中的值就永久地丢失了。

    所以应该先保存x的值：

    { int t = x;  x = y;  y = t;  }
