
    在本题中，主要问题是如何求素数，由于素数的特点是小于且大于１的数都不是被
它整除，故只要把从１到N-1的数逐个验证即可。

    实际上，只要验证到它的平方根就可以了，不过我们没有必要如此麻烦，因为不牵
扯到实用性的问题。不过也可以仅验证到它的一半，这样就确保无误了。

    读者在编程的过程中经常犯的错误是：把０和１也带进去验证，这样的话，前者会
出现除零错误，若是后者，则怎么也发现不了素数了，因为所有的整数都可以被１整除
。

    还有，在向数组中记录素数的时候，不要忘了N++，在开始的时候也不要忘了把N赋
为零。
