
    下列给定程序中，函数fun的功能是：给定n个实数，输出平均值，并统计在平均值
以上（含平均值）的实数个数。例如，n=8时，输入193.199、195.673、295.757、196.0
51、196.092、196.596、196.679、196.763所得平均值为195.838745，在平均值以上的
实数个数应为5。

    请改正程序中的错误，使程序能输出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
