
    学生的记录是由学号和成绩组成，Ｎ名学生的数据已在主函数中放入结构体数组s中
，请编写函数fun，它的功能是：函数返回指定的学号的学生数据，指定的学号在主函数
中输入，若没找到指定学号在结构体变量中给学号置空串，给成绩置-1，作为函数值返
回（用于字符串比较的函数是strcmp）。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
