
    对于一维数组，若要排序需要建立一个二重的循环结构，而仅仅找出最大值，则只
要一重循环就够了。

    这里就要建立一个用于比较的变量，并且若要找最大值，就要首先赋于一个较小的
值，若要找最小值，就要首先赋于一个较大的值。比如说要找出一些学生的最低分数，
这时可以赋于一个100以上的值，若不确定其范围，则对于整型只要赋予0x7fff就可以了
，因为这是整型的最大值。

    这里是二维数组，找出每列中的最小元素，则只要将其看成多个一维数组就可以了
。
