
    这个程序看起来比较长，实际上我们不用管那么多内容，我们只要按照题意将fun函
数编好就可以了。

    实际上这是一个链表的遍历问题，读者在遍历的过程中不要忘了指针的下移，也就
是这个结点访问完后要指向下一个节点。  注意，有的读者可以习惯了用p++，但这里是
不能用p++的，否则会引起较严重的后果。

    还有，在函数的结束处尤其不要忘了有返回值，在返回浮点类型数的时候更要注意
，否则会出现浮点处理错误再终止程序。


