该程序涉及以下几个问题：

１、通常定义函数时要说明数值类型，返回什么结果就定义为什么类型，而不返回数值
的则定义为空类型void；而未标注类型的则默认为int型，例如main()函数便通常不标注
类型。而在该程序中，由于没有返回值，则最好定义为void型，不过这不会造成致命的
错误。

２、其余两处错误是程序中的执行错误，在这些循环结构中分析这些问题，常常感到无
从做起，不过您可以通过直觉来感知到是大于还是小于等，而对于加不加等号的问题，
通常通过代入特殊值的方法来判断。只要多接触一下这类题，您的判断力准会大大增强
。
