
    其实我并不需要您太多的为难，在题目说明中，已经给出了某一项的通用表达式为
1/(2n-1) - 1/(2n);这样只要您按这个思路建立循环就是了。

    要注意：计算某项值的时候不要忘了数据类型的转换，否则出错，就是说不能用：

        sum = 1/(2*k-1) - 1/(2*k);

    这样将变成了整型了。正确的是：

        sum = 1.0/(2*k-1) - 1.0/(2*k);

    后面加上个".0"就相当于将其转化为浮点类型了。
