
    编写函数fun，该函数的功能是：从字符串中删除指定的字符。同一字母的大、小写
按不同字符处理。

    例如：若程序执行时输入字符串为：turbo c and borland c++

    从键盘上输入字符n，则输出后变为：turbo c ad borlad c++
    如果输入的在字符串中不存在，则字符串照原样输出。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，在函数fun的花括号中填入所编写的
若干语句。
