EXAMPATH: 2002
SHOWTIME: 1
SOUND: 1
AUTOLINE: 1
SHINESPEED: 2
MSGSEE: 1
MSGBOXSEE: 1
AUTORESET: 0
AUTOSAVE: 1
DESKFILE: desktop\
DESKBOXCOLOR: 3
EDITBOXCOLOR: 2
SHOWBOXCOLOR: 14
COMPILEBOXCOLOR: 11
HELPBOXCOLOR: 15
BACKCOLOR: 1
WAITFORCLICK: 1
COMPILEMODEL: 0
HEADCOLOR: 3
