
    该例也要首先求出平均分来，然后再进行逐个地比较，把高于平均分的学生资料存
入指定结构体数组中。

    这当然也是两重的循环，第一个循环用来求平均分，第二个循环用来找出符合规定
的成员。

    要注意：结构体是可以直接赋值的。如结构体A与B，可以这样来赋值：A=B；这相当
于把B中的每一个成员都赋予A中的相应成员。

    最后在函数结束前不要忘了返回平均值。否则将造成致命的浮点数自理错误。
