
    如果您会判断素数，那么自然也会判断非素数了。

    判断素数方法是：把从２到n/2的所有数带入判断就可以了，如果都不能被整除，就
是素数。

    实际上只要把小于n的平方根的所有奇数代入判断即可。不过在这里不要求速度，
您最好找一个最简单最直观的编法。

    在该例的参考答案中，笔者提供了一种非常易懂的设计方法，其中判断素数的方法
是这样的：

    for(i=2; i<K; i++)
      if(K%i==0)  break;    //如果找到能整除的则退出来
    if(i!=K)     //该句说明，如果i==K则说明将循环全部执行完才退出的，说明是素
                 //数，否则，便是非素数了。
      ...


