
    实际上遇到这类的问题，自然会想到要建立一个循环，因为这是一定次数的循环，
最好用for。

    在处理浮点数问题上，要特别注意。因为很容易引起浮点数处理错误，例如，在没
有赋值的时候便访问其值等。

    还要注意其类型转化问题。如其中的1.0/f最好不要写成1/f，虽然在这里也能得出
正确的结果，但这并不是万能的，因为在有的数值转化的过程并不尽人心意。

    数据类型的转化也是许多读者经常忽略的问题。还要注意，在处理浮点数的时候，
一般不要进行是否相等的比较，因为这两个数只要相差一丝一毫，也会认为其不相等。

