
    这个问题的关键在于：怎样求字符串的长度，实际上有好多种方法，但原理是一样
的，就是找到最近的字符'\0'距离多远。下面再介绍几种方法：

    一、int N=-1;  while(str[++N]!='\0');  或者：while(str[++N]);

    二、int N=0; char *p=str;  while(*p++)  N ++;

    实际上第二种方法是最快的方法，通过指针的引用，实现地址的自增，从而省略了
下标运算，节省了时间。
