
    该例中，读者应该弄清楚数组的下标的问题，如果把一个字符串从头到尾来排序，
则您可以不会犹豫，但是要忽略首尾的字母，可以你要费点周折了。

    其实不过是把首尾的字母忽略掉而已，也就是说，把字符串下标看成从1到n-2就可
以了。于是便有了：

    for(j=1; j<n-1; j++)
      for(i=j+1; i<n-1; i++)
        ...

    再就是两数值交换的问题，需要用到中间变量，为使代码紧凑，在本例中的参考答
案中，这种风格是比较直观的。否则如果把所有的变量都定义在首部，读者可能不会马
上了解其含义。
