
    这个程序首先考查了读者结构体变量的传递方式，在结构体变量的传递上，一般是
传址方式，即把它的首地址传给函数，在返回的时候，通常也是返回首地址，故在定义
的时候应用这种方法：

    void fun(STREC *ptr);

    也许有的读者会这样来定义：void fun(STREC ptr);  这是无论如何也行不通的。

    再者，考查了读者结构体成员的引用问题：若是通过指针方式引用，则这样写：

             sum = ptr->s;   sum = ptr->s[0];  ...

    若不是指针，则这样引用：

             sum = abc.s;    sum = abc.s[0];  ...

    实际上这就是箭头运算符和成员运算符的区别。不过二者也是相通的，即也可以这
样引用：  sum = (*ptr).s;  sum = (&abc)->sum;  ...

    不过这是有意地绕了一个弯路。  

