
    某学生的记录由学号、８门课程成绩和平均分组成，学号和８门课程的成绩已在主
函数中给出。请编写函数fun，它的功能是：求出该学生的平均分放在记录的ave成员中
。请自己定义正确的形参。

    例如，若学生的成绩是85.5, 76, 69.5, 85, 91, 72, 64.5, 87.5，则他的平均分
应当是78.875。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他中的任何内容，仅在函数fun部位中填入所编写的若干语
句。
