您可能花费了大量的时间找不到结果，而找到结果的时候也会恍然大悟。

这主要有下面几个问题：

１、将for(i=2; i<=m; i++);  误写为：for(i=2; i<m; i++);  实际上这些问题是十分
棘手的，您不妨代几个特殊的数来看一看，而省去了繁琐的推理过程。

２、将y -= 1.0/(i*i);  误写为：y -= 1/(i*i);  这是在编程中经常遇到的错误，仅
仅这一个小小的错误，足以让您耗费大量的时间。实际上这是类型的转换问题：若写成
1.0的形式，则表示其为double型，而写为1则表示为整型，而在自动的类型转换问题中
，总是将其转换为精度最高的形式；您也可以将其改为：y -= (double)1/(i*i);  这样
也会输出正确的结果。

还有：本题中的函数clrscr()的作用是清空屏幕；在printf函数中，格式控制符%lf是指
按double型输出数据，您不要将其中的字母l看成数字1，而感到莫名其妙！
