
    下列给定程序中，函数fun的功能是：统计一个无符号整数中各位数字值为零的个数
，通过形参传回主函数；并把该整数中各位上最大的数字值作为函数值返回。例如，若
输入无符号整数30800，则数字值为零的个数为３，各位上数字值最大的是８。

    请改正函数fun中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！

