
    下列给定程序中，函数fun的功能是：从n个学生的成绩中统计出低于平均分的学生
人数，此人数由函数值反回，平均分存放在形参aver所指的存储单元中。例如，若输入8
名学生的成绩：

    80.5 60 72 90.5 98 51.5 88 64

则低于平均分的学生人数为4（平均分为：75.5625）。

    请改正程序中的错误，使它能统计出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
