
    NULL的意义一般是指针的指向是一个空值，即地址０。而这时用printf来输出时，
则输出"(null)"，空值和空字符串不同，空值是指指向的地址为０，而空字符串则表示
其指向的地址中，其内容为０，这时用printf输出时，并没有显示。

    在Ｃ语言中，变量和常量有大小的区分，于是NULL和Null的含义便不同了。NULL实
际上是一个宏定义，其值为０。

    该程序中的另一个错误又是犯了老毛病：将两个变量的地址拿来做比较，于是就使
其变得没有意义了。今后我们在编程中特别要注意指针型变量和普通型变量的区别。滥
用指针将会造成死机甚至更严重的后果。
