
    下列给定程序中函数fun的功能是：求出在字符串中最后一次出现的子字符串的地址
，通过函数返回，在主函数中输出从此地址开始的字符串：若未找到，则函数值为NULL
。例如，当字符串中的内容为abcdabfabcdx， 和中的内容为ab时，输出结果应是：abcd
x。当字符串中的内容为abcdabfabcdx。t中的内容为abd时，则程序输出未找到信息：
not be found!。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构。
