A#include <stdio.h>
A#include <conio.h>
A#include <stdlib.h>
A
A#define N  5
A
Adouble fun(int w[][N])
A {
H   int i, j, n=0;
H   double sum = 0.0;
H   for(j=0; j<N; j++)
H     for(i=0; i<N; i++)
H       if(i==0 || j==0 || i==N-1 || j==N-1)
H         { n ++;  sum += w[j][i]; }
H   return sum/(double)n;
A }
A
Amain()
A { int a[N][N] = { 0, 1, 2, 7, 9, 1, 9, 7, 4, 5, 2, 3, 8, 3, 1, 4, 5, 6, 8,
A                   2, 5, 9, 1, 4, 1 };
A   int i, j;
A   double s;
A   clrscr();
A   printf("***** The array *****\n");
A   for(i=0; i<N; i++)
A    { for(j=0; j<N; j++)
A       { printf("%4d", a[i][j]); }
A      printf("\n");
A    }
A   s = fun(a);
A   printf("***** THE RESULT *****\n");
A   printf("The sum is : %lf\n", s);
A }
A
