
    下列程序定义了N*N的二维数组。并在主函数中赋值。请编写函数fun，函数的功能
是：求出数组周边元素的平均值并作为函数值返回给主函数中的s。例如：若a中的值为

      ┃０ １ ２ ７ ９┃
      ┃１ ９ ７ ４ ５┃
  a = ┃２ ３ ８ ３ １┃
      ┃４ ５ ６ ８ ２┃
      ┃５ ９ １ ４ １┃
    则返回主程序后s的值为3.375。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
