void  leftbutton_click(int), rightbutton_click(int);
void  deal_l(int), move_l(int, int), insert_l(int);
void  deal_h(int), move_h(int, int), insert_h(int);
void  clear_h(int), clear_l(int), clear_g(int,int);
void  barxy(int, int), arg_in(int,int), mk_order(int);
int   data_cmp(ST_MSG*, ST_MSG*, int), keyboard_click(int);
void  data_chang(ST_MSG*, ST_MSG*),  deal_kind(int);
int   ask_save();
void  write_fp(), write_fl(int), format_msg();
int   find_order(char *);
void  bk_str(char *), move_win(), show_msgnum();