#ifndef KEY_H_2004_12
#define KEY_H_2004_12

#define  LEFT_KEY    	(75<<8)
#define  RIGHT_KEY   	(77<<8)
#define  UP_KEY      	(72<<8)
#define  DOWN_KEY    	(80<<8)
#define  SPACE_KEY   	32
#define  ENTER_KEY   	13
#define  ESC_KEY     	27
#define  TABLE_KEY     	9
#define  BACKSPACE_KEY  8
#define  HOME_KEY    	(71<<8)
#define  END_KEY     	(79<<8)
#define  PAGEUP_KEY  	(73<<8)
#define  PAGEDOWN_KEY   (81<<8)
#define  INSERT_KEY  	(82<<8)
#define  DELETE_KEY  	(83<<8)
#define  F1_KEY      	(59<<8)
#define  F2_KEY      	(60<<8)
#define  F3_KEY      	(61<<8)
#define  F4_KEY      	(62<<8)
#define  F5_KEY      	(63<<8)
#define  F6_KEY      	(64<<8)
#define  F7_KEY      	(65<<8)
#define  F8_KEY      	(66<<8)
#define  F9_KEY      	(67<<8)
#define  F10_KEY     	(68<<8)
#define  F11_KEY     	(133<<8)
#define  F12_KEY     	(134<<8)
#define  SHIFT_F1_KEY   (84<<8)
#define  SHIFT_F2_KEY   (85<<8)
#define  SHIFT_F3_KEY   (86<<8)
#define  SHIFT_F4_KEY   (87<<8)
#define  SHIFT_F5_KEY   (88<<8)
#define  SHIFT_F6_KEY   (89<<8)
#define  SHIFT_F7_KEY   (90<<8)
#define  SHIFT_F8_KEY   (91<<8)
#define  SHIFT_F9_KEY   (92<<8)
#define  SHIFT_F10_KEY  (93<<8)
#define  SHIFT_F11_KEY  (135<<8)
#define  SHIFT_F12_KEY  (136<<8)
#define  ALT_F1_KEY     (104<<8)
#define  ALT_F2_KEY     (105<<8)
#define  ALT_F3_KEY     (106<<8)
#define  ALT_F4_KEY     (107<<8)
#define  ALT_F5_KEY     (108<<8)
#define  ALT_F6_KEY     (109<<8)
#define  ALT_F7_KEY     (110<<8)
#define  ALT_F8_KEY     (111<<8)
#define  ALT_F9_KEY     (112<<8)
#define  ALT_F10_KEY    (113<<8)
#define  ALT_F11_KEY    (139<<8)
#define  ALT_F12_KEY    (140<<8)
#define  CTRL_F1_KEY    (94<<8)
#define  CTRL_F2_KEY    (95<<8)
#define  CTRL_F3_KEY    (96<<8)
#define  CTRL_F4_KEY    (97<<8)
#define  CTRL_F5_KEY    (98<<8)
#define  CTRL_F6_KEY    (99<<8)
#define  CTRL_F7_KEY    (100<<8)
#define  CTRL_F8_KEY    (101<<8)
#define  CTRL_F9_KEY    (102<<8)
#define  CTRL_F10_KEY   (103<<8)
#define  CTRL_F11_KEY   (137<<8)
#define  CTRL_F12_KEY   (138<<8)
#define  CTRL_LEFT_KEY  (115<<8)
#define  CTRL_RIGHT_KEY (116<<8)
#define  CTRL_UP_KEY    (141<<8)
#define  CTRL_DOWN_KEY  (145<<8)
#define  ALT_LEFT_KEY   (155<<8)
#define  ALT_RIGHT_KEY  (157<<8)
#define  ALT_UP_KEY     (152<<8)
#define  ALT_DOWN_KEY   (160<<8)
#define  CTRL_TABLE_KEY (148<<8)

#define  CTRL_A_KEY	1
#define  CTRL_B_KEY	2
#define  CTRL_C_KEY	3
#define  CTRL_D_KEY	4
#define  CTRL_E_KEY	5
#define  CTRL_F_KEY	6
#define  CTRL_G_KEY	7
#define  CTRL_H_KEY	8
#define  CTRL_I_KEY	9
#define  CTRL_J_KEY	10
#define  CTRL_K_KEY	11
#define  CTRL_L_KEY	12
#define  CTRL_M_KEY	13
#define  CTRL_N_KEY	14
#define  CTRL_O_KEY	15
#define  CTRL_P_KEY	16
#define  CTRL_Q_KEY	17
#define  CTRL_R_KEY	18
#define  CTRL_S_KEY	19
#define  CTRL_T_KEY	20
#define  CTRL_U_KEY	21
#define  CTRL_V_KEY	22
#define  CTRL_W_KEY	23
#define  CTRL_X_KEY	24
#define  CTRL_Y_KEY	25
#define  CTRL_Z_KEY	26

#define  ALT_Q_KEY	(16<<8)
#define  ALT_W_KEY	(17<<8)
#define  ALT_E_KEY	(18<<8)
#define  ALT_R_KEY	(19<<8)
#define  ALT_T_KEY	(20<<8)
#define  ALT_Y_KEY	(21<<8)
#define  ALT_U_KEY	(22<<8)
#define  ALT_I_KEY	(23<<8)
#define  ALT_O_KEY	(24<<8)
#define  ALT_P_KEY	(25<<8)
#define  ALT_A_KEY	(30<<8)
#define  ALT_S_KEY	(31<<8)
#define  ALT_D_KEY	(32<<8)
#define  ALT_F_KEY	(33<<8)
#define  ALT_G_KEY	(34<<8)
#define  ALT_H_KEY	(35<<8)
#define  ALT_J_KEY	(36<<8)
#define  ALT_K_KEY	(37<<8)
#define  ALT_L_KEY	(38<<8)
#define  ALT_Z_KEY	(44<<8)
#define  ALT_X_KEY	(45<<8)
#define  ALT_C_KEY	(46<<8)
#define  ALT_V_KEY	(47<<8)
#define  ALT_B_KEY	(48<<8)
#define  ALT_N_KEY	(49<<8)
#define  ALT_M_KEY	(50<<8)

#define  ALT_1_KEY	(120<<8)
#define  ALT_2_KEY	(121<<8)
#define  ALT_3_KEY	(122<<8)
#define  ALT_4_KEY	(123<<8)
#define  ALT_5_KEY	(124<<8)
#define  ALT_6_KEY	(125<<8)
#define  ALT_7_KEY	(126<<8)
#define  ALT_8_KEY	(127<<8)
#define  ALT_9_KEY	(128<<8)
#define  ALT_0_KEY	(129<<8)

#define  RIGHT_SHIFT_STATUS 0x01
#define  LEFT_SHIFT_STATUS  0x02
#define  SHIFT_STATUS       0x03
#define	 CTRL_STATUS        0x04
#define  ALT_STATUS         0x08
#define  SCROLL_STATUS      0x10
#define  NUM_STATUS         0x20
#define  CAPS_STATUS        0x40
#define  INSERT_STATUS      0x80

#define  ESC_CODE			0x01
#define  F1_CODE            0x3B
#define  F2_CODE			0x3C
#define  F3_CODE			0x3D
#define	 F4_CODE			0x3E
#define  F5_CODE			0x3F
#define  F6_CODE			0x40
#define  F7_CODE			0x41
#define  F8_CODE			0x42
#define  F9_CODE			0x43
#define  F10_CODE			0x44
#define  F11_CODE			0x57
#define  F12_CODE			0x58
#define  WAVE_CODE			0x29
#define  NUM1_CODE			0x02
#define	 NUM2_CODE			0x03
#define  NUM3_CODE			0x04
#define  NUM4_CODE			0x05
#define  NUM5_CODE			0x06
#define  NUM6_CODE			0x07
#define  NUM7_CODE			0x08
#define  NUM8_CODE			0x09
#define  NUM9_CODE			0x0A
#define  NUM0_CODE			0x0B
#define  MINUS_CODE			0x0C
#define  EQUAL_CODE			0x0D
#define  PLUS_CODE			0x0D
#define  VERTICAL_CODE      0x2B
#define	 BACKSPACE_CODE		0x0E
#define  TABLE_CODE			0x0F
#define  Q_CODE				0x10
#define  W_CODE				0x11
#define  E_CODE				0x12
#define  R_CODE				0x13
#define  T_CODE				0x14
#define  Y_CODE				0x15
#define  U_CODE				0x16
#define  I_CODE				0x17
#define  O_CODE				0x18
#define  P_CODE				0x19
#define  LEFT_SQUARE_CODE   0x1A
#define  RIGHT_SQUARE_CODE  0x1B
#define  ENTER_CODE			0x1C
#define  CAPSLOCK_CODE		0x3A
#define  A_CODE				0x1E
#define  S_CODE				0x1F
#define  D_CODE				0x20
#define  F_CODE				0x21
#define  G_CODE				0x22
#define  H_CODE				0x23
#define  J_CODE				0x24
#define  K_CODE				0x25
#define  L_CODE				0x26
#define  SEMICOLON_CODE		0x27
#define  QUOTATION_CODE		0x28
#define  LEFT_SHIFT_CODE	0x2A
#define  Z_CODE				0x2C
#define  X_CODE				0x2D
#define  C_CODE				0x2E
#define  V_CODE				0x2F
#define  B_CODE				0x30
#define  N_CODE				0x31
#define  M_CODE				0x32
#define  COMMA_CODE			0x33
#define  SAMLLER_CODE		0x33
#define  PERROD_CODE		0x34
#define  GREATER_CODE		0x34
#define  QUESTION_CODE		0x35
#define  BIAS_CODE			0x35
#define  RIGHT_SHIFT_CODE	0x36
#define  CTRL_CODE			0x1D
#define  ALT_CODE			0x38
#define  SPACE_CODE			0x39
#define  SCROLLLOCK_CODE    0x46
#define  PAUSE_CODE			0x1D
#define  BREAK_CODE			0x1D
#define  INSERT_CODE        0x52
#define  DELETE_CODE		0x53
#define  HOME_CODE			0x47
#define  END_CODE			0x4F
#define  PAGEUP_CODE		0x49
#define  PAGEDOWN_CODE		0x51
#define	 UP_CODE			0x48
#define  DOWN_CODE			0x50
#define  LEFT_CODE			0x4B
#define  RIGHT_CODE			0x4D
#define  NUMLOCK_CODE		0x45
#define  ASSIST_STAR_CODE	0x37
#define  ASSIST_MINUS_CODE  0x4A
#define  ASSIST_PLUS_CODE	0x4E
#define  ASSIST_MIDDLE_CODE 0x4C
#define  ASSIST_BIAS_CODE   0x35
#define  ASSIST_HOME_CODE   0x47
#define  ASSIST_END_CODE	0x4F
#define  ASSIST_UP_CODE     0x48
#define  ASSIST_DOWN_CODE	0x50
#define  ASSIST_LEFT_CODE	0x4B
#define  ASSIST_RIGHT_CODE  0x4D
#define  ASSIST_PAGEUP_CODE 0x49
#define  ASSIST_PAGEDOWN_CODE 0x51
#define  ASSIST_INSERT_CODE 0x52
#define  ASSIST_DELETE_CODE 0x53
#define  ASSIST_ENTER_CODE  0x1C

#include "Object.h"

enum KEYSIDE
{
	KEYSIDE_LEFT,
	KEYSIDE_RIGHT,
	KEYSIDE_DEFAULT
};

enum KEYTYPE
{
	KEYTYPE_UP,
	KEYTYPE_DOWN,
	KEYTYPE_PRESS,
	KEYTYPE_DEFAULT
};

enum KEYPOSTION
{
	KEYPOSTION_NORMAL,
	KEYPOSTION_ASSIST,
	KEYPOSTION_DEFAULT
};

typedef unsigned char KEYSTATE;

class KeyBoard : virtual public Object
{
public:
	KeyBoard();
	virtual ~KeyBoard();

protected:
	unsigned int GetKeyPress();

public:
	static void interrupt (far *oldkey)(...);
	static void interrupt far newkey(...);
	static unsigned int counterforsetvect;

private:
	static struct KeyItem
	{
		KeyItem();
		unsigned int KeyCode;
		unsigned char KeyState;
		KeyItem *next, *previous;
	} *Point, *End;

private:
	static KEYSIDE 		keyside;
	static KEYTYPE	 	keytype;
	static KEYPOSTION	keypostion;
	static KEYSTATE	    keystate;
	static BOOL	   		ismeet0xe0;
	static unsigned int keycode;

protected:
	KEYSIDE    GetKeySide() { return keyside; }
	KEYTYPE    GetKeyType() { return keytype; }
	KEYPOSTION GetKeyPostion() { return keypostion; }
	KEYSTATE   GetKeyState(unsigned char state=0xFF) { return keystate & state; }
	unsigned int GetKeyCode() { return keycode; }
	unsigned int TranslateKey(unsigned int key);
};

#endif