A#include <conio.h>
A#include <stdio.h>
A#include <string.h>
A
Avoid fun(char *s, char t[])
A {
H   int k, L = strlen(s), N=0;
H   for(k=0; k<L; k++)
H     if(k%2==0 && s[k]%2==0)  t[N++] = s[k];
H   t[N] = '\0';
A }
A
Amain()
A { char s[100], t[100];
A   clrscr();
A   printf("\nPlease enter string S:");  scanf("%s", s);
A   fun(s, t);
A   printf("\nThe result is : %s\n", t);
A }
