
    请编写函数fun，其功能是：将s所指字符串中除了下标为偶数，同时ASCII值为为偶
数的字符外，其余的全部删除，串中剩余字符所形成的一个新串放在t所指的数组中。

    s民指字符串中的内容为ABCDEFG123456，其中字符A的ASCII码值为奇数，因此应当
删除；其中字符B的ASCII码为偶数，但在数组中的下标为奇数，因此也应该删除；而字
符2的ASCII码值为偶数，所在数组的下标也为偶数，因此不应当删除，其他依此类推。
最后t所指的数组中的内容应是246。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
