A#include <conio.h>
A#include <stdio.h>
Avoid fun(int a, int b, long *c)
A {
H   *c = (b/10)*1000 + (a/10)*100 + (b%10)*10 + (a%10);
A }
A
Amain()
A { int a, b;  long c;
A   clrscr();
A   printf("Input a, b:");
A   scanf("%d%d", &a, &b);
A   fun(a, b, &c);
A   printf("The result is: %ld\n", c);
A }
