
    本例中，思路稍显复杂，不过理清思路后觉得也很简单，既然是迭代法，那么就必
然会有一个变量为控制循环，而这里的变量必须定义为double型。

    仔细观察每一项，下一项是前一项乘以K/(2K+1)，于是便可定义double型变量K，让
K渐增，然后下一项乘以K/(2K+1)就行了。

    当某一项小于eps的时候就可以退出，自然有了while(d>eps);于是程序的框架很容
易就构建起来了。
