
    对于这道题，对大多数读者来说就显得有点复杂了，因为我们以前接触过二重循环
，是在排序过程中的。而现在则是一个三重循环。

    第一重循环，把所有的数都遍历

    第二重循环，检查以后有和当前数重复的数据

    第三重循环，若发现重复数据，则从当前位置循环到末尾来删除重复数据

    该例的难点还是在于循环次数的控制，若一次不能达到目的，读者可以观察运行结
果，再推断到底错在哪里。
