
     短短的几行代码也可以让你费尽心思，您可曾想到：把一个数四舍五入的方法是：
把一个小数保留n位且四舍五入的方法是：把n+1位升高５个单位，然后再将n+1位及以后
的位抛弃即可。

    在这个例子中，笔者先将其乘以100，于是原来的小数１位和２位皆变为整数部分了
然后再将其按整型转化，这就会丢弃了所有的小数，然后再将其除以１００，这样，原
来的整数部分的百位和个位，就变成小数部分的十分和百分位了。

    这个例子只是用了一个小小的技巧而已，而对于大多数的读者可以要想到取余，不
过笔者告诉您，对于浮点数是不可以用%取余的，不过您可以用取余函数mod，只是原题
中头文件并没有包含<math.h>，于是您只好作罢了，况且，取余也只是一个近似的运算
，您不能保证会将其多余的位全部丢弃。
