
    这是一个很典型的字符串移动的问题，实际上如果借助于字符串函数，很容易将问
题解决。而题目中已经明确禁止，我们也只好自己麻烦点了。

    首先要明确前面有几个星，如果得出结果为K，那么下一步就是把后面的字符向前移
K个距离了。这用到了两个循环，因为皆是不定次数的循环，故用到了while而没有用for
。
    接下来，就是把前面的星补到后面去，实际上就是在后面加上K个星而已。在这里笔
者巧妙地利用了上面循环带来的结果ptr，因为它现在正是指向结尾'\0'，只要把ptr向
前移一格，再接着用for循环进行K次赋值，就可以把K个星号连接在最后了。

    最后别忘了把字符串的结尾再加上'\0'，这恐怕是大多数读者爱犯的错误！
