
    这个程序也许有些棘手，如果仔细分析的话，其实也容易理清其思路。

    首先，要从首部开始寻找空格，如果遇到空格，便把后面的值依次向前赋，这样读
者也许很容易想到建立for循环。

    但在这里牵扯到一个问题，这里的循环次数是不固定的，也许读者会问：不就是字
符串的长度嘛！可是，当连续删除空格之后，字符串的长度就变了，所以只要这时候再
纠正字符串的长度，这样虽然麻烦，但也是行得通的。

    于是便想到了while，因为while是控制不定次数循环的。条件只要是遇到'\0'便退
出就可以了。

    读者可以仔细阅读笔者提供的参考答案，相信您会明白这种算法的。

    在这里提醒读者：在控制指针的时候，不要把while(*p)写成了while(p)，这样可以
要循环不停，把系统中的内容也给破坏了。也不要把后面的p++写成了(*p)++。更不要忘
了写，否则程序将变成了死循环。

    所以在使用指针的时候一定要特别小心。
