
    所谓周边元素，是指矩阵中在周围的元素，这些元素的特点就是：或者横坐标值为
零或最大，或者纵坐标值为零或最大，抓住这个特点，就可以从二维数组值的下标值中
找规律了。

    于是便有了语句：if(i==0 || j==0 || i==N-1 || j==M-1) ...

    再一个要点，凡是求和的程序中，千万别忘了要有一个变量来记录和值，并且这个
变量要先赋初值为零，否则，将会得出不可预料的结果来。

    还有，数组的尽头是元素数减１，就是说，int a[10]中，数组下标的范围实际上是
从0到9，而对于a[10]，则“超标”了，但是编辑器不会检测了来，要是对a[10]赋值的
话，将会出现不可预料的结果。

