该程序中的错误属于书写格式错误。

第一处错误中：将 IsPrime(int n)  误写为 IsPrime(int n);  仅一个分号之差，编译
程序就会将这条语句解释为函数的声明，而后面的大括号内的内容便成为一个“无头”
的函数，于是编译错误！

第二处错误中：将 if(!(n%i)) 误写为 if !(n%i)，受BASIC编程的影响，读者经常会将
忘记这对括号，但是Ｃ语言是比较规范的语言，if后面的内容必须有括号引起来，否则
会出现编译的格式错误！

这两处错误都属于比较浅显的错误，经常在编译器报告出错时，您便可以查出来。但这
类试题在考题中比较少见！
