
    这个问题不过是拐了点弯，仅转换奇数位置上的内容。这样您的头脑就也要转一个
弯了。首先不应该转换０位置上的元素，应该从第１个开始。而这时有的读者可以会习
惯地用递增了。如 for(k=1; k<Len; k++)，这是由于习惯性的思维所致，使程序不能运
行出正确的结果。

    正确的应该是：for(k=1; k<Len; k+=2);这样就能保证访问到所有奇数位上的元素
了。

    再者，大小写的字母ASCII值相差32，且小写字母的ASCII值要大。若是读者实在忘
记了差值的时候，也可以用'a'-'A'来表示。
