
    数列中，第一项值为３，后一项都比前一项的值增５；下列给定程序中，函数fun的
功能是：计算前n(4<n<50)项的累加和；在累加过程中把那些被４除后余２的当前累加值
放入中，符合此条件的累加值的个数作为函数值返回主函数。例如，当n的值为20时，该
数列为3,8,13,18,23,28,..,93,98。符合此条件的累加值应为42,126,366,570,1010。

    请改正函数fun中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
