
    在尾部删除字符实际上和在中间删除字符是不同的，因为它不需要移动，只要把后
面要删除的字符中，最前面一个赋为'\0'即可。

    在这个程序中，笔者先运用了从尾部开始向前寻找的方法，来找到首先出现字母的
位置。这样把从这个位置向后数n+1个字符赋为'\0'就可以了，不过这种方法要在保证字
符串足够长的情况下，以避免出现越界。更安全的办法是在此加以检测，是否超出了界
限，然后再赋零。
