A#include <stdio.h>
A#include <conio.h>
A
Avoid fun(char *a)
A {
H   char *ptr = a, *ptr0 = a;
H   while(*ptr++=='*');
H   ptr --;
H   while(*ptr0++ = *ptr++);
A }
A
Amain()
A { char s[81];
A   printf("Enter a string:\n"); gets(s);
A   fun(s);
A   printf("The string after deleted:\n");  puts(s);
A }
