
    这并不复杂，只要用通过指针来访问数组中的每一个元素，只要这个元素和它的下
一个元素都和指定字符相同，则计数值增１。

    最后返回计数器的值就可以了。

    不过聪明的读者也可以会发现这样一个问题：如果在字符串CCCAAABBBCCC中寻找字
符串CC的个数，到底是两个还是四个呢，笔者编写的这个参考答案将会寻找出四个来，
不过到底应该是几个也许就没有人会拿主意了。
