在此程序中，出错的都是一些小错误，一般情况下，编译错误很容易被发现，而执行错
误却要费一番周折。

１、第一处，函数在没有返回值的情况下，最好定义为void型，但这不会引起致命的错
误。
２、第二处，while(r) 和 while(*r)是截然不同的，前者是引用的地址，而后者是引用
的内容。
３、第三处，在此语句中漏掉了分号，凡是漏掉括号和分号的语句在编译过程中很容易
被发现，在错误信息中会有明确的提示。
