
    下列给定程序中，函数fun的功能是：将s所指字符串中出现的t1所指子串全部替换
成t2所指子字符串，所形成的新串放在w所指的数组中。在此处，要求t1和t2所指字符串
的长度相同。例如，当s所指字符串中的内容为abcdabfab，t1所指子串中的内容为ab，t
2所指子串中的内容为99时，结果，在w所指的数组中的内容应为99cd99f99。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得璨改程序的结构！
