
    这道题看起来比较繁琐，但细细研究起来也并不复杂，无非是求方差而已。

    首先要求出算术平均值，要注意在开始的时候要把和值赋为零。

    其次再逐个求其与平均值的差的平方。

    最后调用库函数sqrt来求出其十分之一的平方根就行了。

    在这个题中用了两次循环结构。库函数sqrt()是用来求一个数的平方根的，它的参
数只有一个，是double型的，返回值也是double型的，在调用的时候要确保参数不为负
值，否则出错。

    若读者在考试过程中忘了哪个是求平方根的参数，可以查看Turbo C 2.0的帮助系统
。
