
    这种题目的关键在于如何建立循环，您可以只检查那些下标为奇数的，不过为了更
明了，倒还不如每一个都检查，这样更直观一些。

    笔者提供的这个标准答案，便是用了一种一目了然的方法。因为在二级考试中的编
程，并不要求程序运行有多高的速度，况且它的循环次数也比较少，所以用这种方法来
编写更为通俗易懂。

    判断奇偶的方法便是用２来取余，看看是否为零，是零则为偶数，否则为奇数。
