
    请编写函数fun，其功能是：将s所指字符串中下标为偶数同时ASCII值为奇数的字符
删除，s中剩余的字符形成的新串放在t所指的数组中。

    例如，若s所指字符串中的内容为：ABCDEFG12345，其中字符C的ASCII码值为奇数，
在数组中的下标为偶数，因此必须删除；而字符1的ASCII码值为奇数，在数组中的下标
也为奇数，因此不应当删除，其他依此类推，最后t所指的数组中的内容应是BDF12345。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
