
    既然这道题牵到了大量数据的移动，不妨先定义一个数组来保存即将移动的数据。

    先把前面的p+1个数据保存下来，然后把从下标为p+1及之后的所有数据向前移动p+1
个单位，然后再把保存下来的数据添到末尾即可。

    读者可能把握不好移动数据的个数及移动的距离，这只有靠您自己来细细思索了，
不过要建立循环，这是必然的。至于什么样的循环好用，您自己就来显显身手吧。

    或许你还可以找到更直观，更简洁的算法，一题多解也是开发创新思维的重要途径
。

