
    请编写函数fun，该函数的功能是：移动一维数组中的内容；若数组中有n个整数，
要求把下标从0到p(p小于等于n-1)的数组元素平移到数组的最后。

    例如，一维数组中的原始内容为1,2,3,4,5,6,7,8,9,10；p的值为3。移动后，一维
数组中的内容应为：5,6,7,8,9,10,1,2,3,4。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
