
    该例中，首先想到要建立一个循环，计算出平均分，再建立一个循环，检测数组的
各个元素，并且要建立一个变量保存最小值。

    要注意，保存最小值的变量在最初时要赋于一个足够大的值，这是这种程序比较常
用的方法。

    再者，把低于平均分的成绩依次放在数组中，这时就要想到建立一个变量来标志数
组中的各个元素，并且变量的值应该自增。

    最后再返回低于平均分的人数。


