
    m个人的成绩存放在score数组中，请编写函数fun，它的功能是：将低于平均分的人
数作为函数值返回，将低于平均分的分数放在bdlow所指的数组中。

    例如，当score数组中的数据为10、20、30、40、50、60、70、80、90时，函数返回
的人数应该是4, below中的数据应为10、20、30、40。

    注意：部分源程序给出如下：

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
