
    数据的类型通常是很容易被忽视的问题，在本题中，若定义r为int型，则无论如何
运算它总是一个整型，而不可能带小数。于是提醒您：在改错题中，凡是带有float型、
double型的题，一般总会有数据类型的错误，这时您一定要注意。

    另外，在本题中又遇到了是大于还是小于的问题，您可能经常绕不过这个弯来，这
就需要您多加练习了。要注意while语句是在条件成立的情况下才继续循环的。
