
    请编写函数fun，该函数的功能是：将M行N列的二维数组中的字符数据，按列的顺序
依次放到一个字符串中。

    例如，若二维数组中的数据为：

    W W W W
    S S S S
    H H H H

    则字符串中的内容应是WSHWSHWSH。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他中的任何内容，仅在函数fun的花括号中填入所编写的若
干语句。
