在该程序中，牵扯到这样几个问题：

１、将int k=0; 误写为int k=1;  这主要考查您数组的下标是从０开始的还是从１开始
的，如语句int a[10];中。数组的下标应为０～９；

２、将while(*p||*q) 误写为 while(*p!=*q)，仅一个运算符之差，意义全变。前者为
当*p与*q之中任一个不为零则继续循环，实际上是while(*p!=0 || *p!=0)，您以后会经
常发现这种表示方法：如if(flag) ...;  实际上就是if(flag!=0) ...;；而后者则为当
*p与*q不相等的时候就继续循环，这显然是错误的。

３、将if(*p<=*q) 误写为 if(*p<*q)，这与您对题意的了解有关，在题意中已经明确指
出了“大或相等”，所以在审题时一定要留意。您在考试过程中若感到束手无策，不妨
细细地读题，说不定灵感会马上到来。

还有，您应该知道：小写字母的ASCII值要比大写字母的ASCII大，如果您不明白这个，
您可能会对一些无误的行痛下杀手，如把大于改为小于等。您应该记住几个重要字母的A
SCII值，若在考试中实现忘了其值，也可用'A'、'a'等表示，还有应该知道，对应大小
写字母的ASCII值之差为32。
