
    下列给定程序中，函数fun的功能是：逐个比较a、b两个字符串对应位置中的字符A
SCII值大或相等的字符依次存放到c中，形成一个新的字符串。例如：若a中的字符串为
：aBCDeFgH，b中的字符串为：ABcd，则c中的字符串应为：aBcdeFgH。

    请改正程序中的错误，使它能得出正确结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序结构。
