
    下列给定程序中，函数fun的功能是：根据整型形参n，计算如下公式的值。

    Ａ1 = 1,  Ａ2 = 1/(1+Ａ1), Ａ3 = 1/(1+Ａ2), ... , Ａn = 1/(1+Ａ(n-1))

    例如：若n=10，则应输出0.617977。

    请改正程序中的错误，使它能得到正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
