
    下列给定程序中，函数fun的功能是：计算并输出下列级数的前Ｎ项之和ＳN，直到
Ｓ(N-1)大于q为止，q的值通过形参传入。

    ＳN = 2/1 + 3/2 + 4/3 + ... + (N+1)/N

    例如，若q的值为50.0，则函数值为49.394948。

    请改正程序中的错误，使程序能输出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！


