
    下列给定程序中，函数fun的功能是：将字符串p中的所有字符复制到字符串b中，要
求每复制三个字符之后插入一个空格。例如，在调用fun函数之前给字符串a输入ABCDEFG
HIK，调用函数之后，字符串b中的内容则为ABC DEF GHI JK。

    请改正程序中的错误，使它能得出正确结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构。
