
    下列给定程序中，fun函数的功能是：求s = aa...aa - ... - aaa - aa - a，（此
处aa...aa表示n个a，a和n的值在1至9之间）。例如a = 3，  n = 6，  则以上表达式为
：
    s = 333333 - 33333 - 3333 - 333 - 33 - 3 ;

    其值是296298。a和n是fun函数的形参，表达式的值作为函数值传回main函数。

    请改正程序中的错误，使它能出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
