这个程序在练习方面并没有多大的意义，仅是把数字0写成字符o而已，不过它可以让您
了解一种编程的思路：就是字符'0'~'9'和数字0~9是相差'0'-0的关系。这通常用在把字
符串转化为数字的形式：例如下面这个程序将把字符串"123"转化为数字123，最后以整
型方式输出：

#include <string.h>
main()
 { char str[] = "123"
   int len = strlen(str), k, Num=0;
   for(k=0; k<len; k++)  Num = Num*10 + (str[k]-'0');
   printf("The result is: %d", Num);
 }

还有：在转化时，应以每位数字乘以基数的相应次幂，所以在本题中，既然已经说明了
是八进制，便不应该乘以７，而应乘以８。
