
    也许您会建立一个长长的switch...case结构，这是可行的，不过这是没有必要的，
因为像这种有规律的下标，完全可以用除10的办法来计算出来。

    不要忘了，当下标超过10的时候，一定要将其赋为10，否则下标就越界了。

    在开始的时候也不要忘了把记录个数的数组赋为零值。

    程序中提供的rnd函数是产生随机数的函数，这是随机数的一种定义方法，读者不要
感到不可思议。虽然实际上产生的数值并不是随机的，但它总也符合随机数的特性。不
过要是真编一个可以产生完全随机数的函数是不可能的。
