
    请编写函数fun，该函数的功能是：统计各年龄段的人数。Ｎ个年龄通过调用随机函
数获得，并放在主函数的age数组中；要求函数把０到９岁年龄段的人数放在d[0]中，把
10至19岁年龄段的人数放在d[1]中，把20至29岁年龄段的人烽放在d[2]中，其余依此类
推。把100岁（含100）以上年龄的人数都放在d[10]中。结果在主函数中输出。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
