在该程序中，有下列一些问题：

１、将void fun(char *s, int *a, int *b); 误写为： void fun(char *s, int a,
int b);  这是用指针进行参数传递的问题，当一个函数有多个返回值时，通常用指针的
办法直接通过地址来改变变量。所以这种方法传递过来的实际上是参数的地址，于是在
定义上，显然题中是错误的。

２、将(*a)++;误写为a++;  将(*b)++;误写为b++;  由于在传址函数（通过地址传递参
数的函数）中，需要通过地址来改变参数，首先应该明确a和b都是指针类型，即它们都
表示地址，故题中引用显然是错误的。

还有应该注意，通常您会发现２中所述的错误，但您可能会将其改为*a++; *b++;  这样
也是错误的，因为自增自减运算符的优先级要高于指针运算符，故编译程序将其解释为
：*(a++); *(b++);  这样不但不会出正确的结果，而且容易造成死机！所以您在应用指
针的时候要格外地小心。
