A#include <stdio.h>
Adouble fun(int n)
A {
H   int k;  double sum = 0.0;
H   for(k=1; k<=n; k++)
H     if(k%9==0 || k%5==0)
H        sum += 1.0/k;
H   return sum;
A }
A
A
Amain()
A { int n;  double s;
A   printf("\nInput n:  ");  scanf("%d", &n);
A   s = fun(n);
A   printf("\n\ns = %f\n", s );
A }
