
    这又是一个数列求和的问题，不过在这里已经指定的循环的次数，故最好建立一个
for循环。

    要注意一点：参考答案中的1.0/(n*(n+1))，也许许多读者会写成1/(n*(n+1))，这
样将变为了整型，达不到预期的结果。

    浮点型的数据类型是非常值得重视的一个问题，通常也会出现在改错题中，若在改
错题中涉及到浮点型，读者就要看一看有没有类型的转化错误。

    在函数结束前不要忘了返回值，否则将出现致命的浮点数据处理错误。
