
    编写函数fun，它的功能是：计算并输出下列级数和：

           １      １                  １
    Ｓ =  ━━ ＋ ━━ ＋ ……… ＋  ━━━
          1×2    2×3               n(n+1)

    例如：当n=10时，函数值为0.909091。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容， 仅在函数fun的花括号中填入所编
写的若干语句。
