
    （１）在传递二维数组时，一定要指明数组的行值，即要求指明a[][M]中的M。而前
面方括号中的数字则无所谓，系统不予理睬。或者可用(*a)[M]的形式。

    （２）在引用下标的时候要注意其值的范围为从零开始的。

注意：在教育部考试中心提供的标准答案中，将(*a)[M]写为*a[M]，这样是错误的，因
为下标的优先级要高到*号，编译系统将给其解释为指针数组。而前者则解释为指向数组
的指针。
