
    下列给定程序中，函数fun的功能是：根据形参m的值（2<=m<=9），在m行m列的二维
数组中存放如下所示的数据，由main函数输出。

    例如，若输入２        ┃  若输入４
          则输出：        ┃  则输出：
              １  ２      ┃          １  ２  ３  ４
              ２  ４      ┃          ２  ４  ６  ８
                          ┃          ３  ６  ９  12
                          ┃          ４  ８  12  16
   请改正程序中的错误，使它能得出正确的结果。

   注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
