
    （１）形参也必须要有说明形式。它可以有以下两种类型：
         (1) int fun(int n) { ... }
         (2) int fun(n) int n; { ... }
         两者是等价的，要求在参数复杂时可以用后者，而比较简单的最好使用前者。

    （２）双等号和单等号是不同的，前者表示判断是否相等，而后者用于给变量赋值
。

