
    请编写函数fun，该函数的功能是：移动字符串中的内容，移动的规则如下：把第1
到第m个字符，平稳到字符串的最后，把第m+1到最后的字符移到字符串的前部。

    例如，字符串中原有的内容为ABCDEFGHIJK，m的值为3，移动后，字符串中的内容应
该是DEFGHIJKABC。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。
