
    在这个程序中，如果使用字符串的库函数，则将变得很简单，只不过原题中并没有
包含字符串库函数，所以只好用这种方法来解了。

    您可否注意到笔者提供的参考答案中，每一次循环，Ｋ值都会增加２，并且每增一
次都会检测是否遇到了'\0'，以免漏过！

    还有，注意小写字母变为大写字母的方法是ASCII值减去32。

    您可以再试一下别的方法，或许有比这更简洁的呢！


