
    请编写一个函数void fun(int m, int k, int xx[]), 该函数的功能是：将大于整
数m且紧靠m的k个素数存入xx所指的数组中。

    例如，若输入：17, 5，则应输出：19、23、29、31、37。

    注意：部分源程序给出如下。

    请勿改动主函数main和其他函数中的任何内容，仅在函数fun的花括号中填入所编写
的若干语句。

