
     下列结定程序中，fun函数的功能是：根据形参m，计算如下公式的值。

     t = 1+ 1/2 + 1/3 + 1/4 + ... +1/m

     例如：若输入５，则应输出2.283333。

     请改正程序中的错误，或在横线处填上适当的内容，（并把横线删除），使它能计
算出正确的结果。

     注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！


