
      本例中，是寻找可以被某数整除的数，这种问题比较简单。读者很容易便可构想
一个循环的框架，把这些数逐个进行验证。

      要注意的几点是：本例中通过指针来返回个数，在引用的时候，不要忘了先把*n
赋为零，即 *n = 0;

      再者，不要忘记*n有个自增的过程，不然全都写到数组中第一个数上去了。在自
增的时候不要用*n++，因为这是地址自增而不是变量自增，应该写为(*n)++。

      还有，在用指针对变量进行引用的时候不要忘了在前面加*。否则则变为地址了。
