
    本例中，笔者提供了一种十分简便明了，但并不通用的办法，相信读者能够一目了
然。

    这题的关键所在是：您不能遍历矩阵中的每一个元素。有好多读者这样来编：

      for(j=0; j<3; j++)
        for(i=j; i<3; i++)
          { int t=array[j][i];
            array[j][i] = array[i][j];
            array[i][j] = t;
          }

    这样编的结果是，当遍历完一半的时候，数据已经互换完毕，当遍历结束的时候，
矩阵又互换过来了，于是又恢复了原貌。这是一个不易发现的问题，有可能让你在考试
的时候感到束手无束。
