A#include <stdio.h>
A#include <string.h>
A#include <conio.h>
A
Avoid fun (char s[], int n)
A { char a[80], *p;
A   int i;
L   s = p;
H   p = s;
A   for(i=0; i<n; i++)   a[i] = '*';
A   do
A    { a[i] = *p;
L      i ++;
H      i ++; p ++;
A    } while(*p);
A   a[i] = 0;
A   strcpy(s, a);
A }
A
Amain()
A { int n;   char s[80];
A   clrscr();
A   printf("\nEnter a string :");  gets(s);
A   printf("\nThe string %s\n", s);
A   printf("\nEnter n (number of *): ");  scanf("%d", n);
A   fun(s, n);
A   printf("\nThe string after inster : %s\n", s);
A }
