
    （１）将赋值的方向搞反，也许是您易犯的错误。

    （２）可知，若仅i自增而p不变，则达不到依次赋值的结果，并且这样将会造成死
循环。

注意：在教育部考试中心提供的标准答案中，将第一行中的char s[]改为char *s，笔者
认为这是无所谓的，因为二者完全等价。

也将下面的a[i]=0改为了a[i]='\0'，这也是没有必要的，因为'\0'的ASCII值实际上就
是0。
