A#include <conio.h>
A#include <stdio.h>
A#include <string.h>
A
Lint fun(char *s, char *t1, char *t2, char *w)
Hvoid fun(char *s, char *t1, char *t2, char *w)
A { int i;  char *p, *r, *a;
A   strcpy(w, s);
L   while(w)
H   while(*w)
A    { p = w;  r = t1;
A      while(*r)
A        if(*r==*p)
A          { r++;  p++; }
A        else break;
A      if(*r=='\0')  a = w;
A      w++;
A   }
A  r = t2;
A  while(*r)  { *a = *r;  a ++;  r ++; }
A }
A
Amain()
A { char s[100], t1[100], t2[100], w[100];
A   clrscr();
A   printf("\nPlease enter string S:");  scanf("%s", s);
A   printf("\nPleae ener substring t1:"); scanf("%s", t1);
A   printf("\nPlease enter substring t2:"); scanf("%s", t2);
A   if(strlen(t1)==strlen(t2))
A     { fun(s, t2, t2, w);
A       printf("\nThe result is : %s\n", w);
A     }
A   else printf("\nError: strlen(t1)!=strlen(t2)\n");
A }
