
    下列给定程序中，函数fun的功能是：将s所指字符串中最后一次出现的，t1所指子
串替换成t2所指子串，所形成的新串放在w所指的数组中。在此处，要求t1和t2所指字符
串的长度相同。例如，当s所指字符串中的内容为abcdabfabc，t1所指子串中的内容为ab
，t2所指子串中的内容为99时，结果，在w所指的数组中的内容应为abcdabf99c。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
