
    （１）在带参的宏定义中，要注意使用括号，因为它只是一种简单的替换。

    如 #define FU(m, n)  (m/n)
    若遇到FU(a+b, a-b)时，则解释成：a+b/a-b;  即：a + b/a + b;
    而 #define FU(m, n)  ((m)/(n))时，则可解释成：(a+b)/(a-b);

    再者，宏定义后面不要再加上分号，且FU和后面的括号之间不可加空格，否则就把
单纯的FU解释成(m, n)  (m/n)了。

    （２）此为书写错误。

