
   Ｎ个有序整数数列已放在一维数组中，给定下列程序中，函数fun的功能是：利用折
半查找算法查找整数m在数组中的位置。若找到，则返回其下标值；反之，则返回-1。

   折半查找的基本算法是：每次查找前先确定数组中待查的范围：low 和 high(low<
high)，然后把m与中间位置(mid)中元素的值进行比较。如果m的值大于中间位置元素中
的值，则下一次的查找范围放在中间位置之后的元素中；反之，下一次的查找范围落在
中间位置之前的元素中。low>high直到查找结束。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构。
