
    此为指针的应用，利用传址方式来实现实际参数的交换。

注意：在教育部考试中心提供的标准答案中，并没有改动前面的*k，而是把后面的k全部
加上了星号，这样改是错误的。可能程序会一时运行正确，但有时会发生死机现象，因
为仅定义了指针k，但并没有规定它指向哪里，这样便应用的话，会发现覆盖掉内部有用
内容的现象，故易死机。

通常，程序有的时候运行正确，但偶尔会运行出错，造成死机，这一般是其中的指针迷
失了方向。读者一定要注意，在使用指针存取内容时要先规定其指向。

如：int k;
    int *p = &k;

    *p = 3;

    若没有第二句的赋值，则易造成死机。
