
    敬爱的老师，亲爱的同学们，你们好！
　　首先预祝您在新的学期中有一个好的开端，能够取得更大的成就。

　　由济南大学材料系学办负责开发的“全国计算机等级考试（二级Ｃ语言）”NCR2学习软件在二零零二年九月问世，本软件直接面向计算机二级考试中的编程题和改错题，并随之携带二百余套标准试题，且附有准确的答案和详解。由于每年Ｃ语言考试中，编程题和改错题是失分的重点。只要您认真对待本题库中的例题，相信您的Ｃ语言编程会如虎添翼。

　　本软件在Window95/Windows98或DOS下运行，在DOS下请先运行鼠标驱动程序MOUSE.COM。它需要鼠标的支持，提供了生动模拟Windows的界面，使您的学习增加了趣味。且不需要再带有Turbo C 2.0软件，本软件可以直接实现编辑编译连接和运行。若您实在不习惯于本软件的编辑环境，可以点击“Turbo C按钮”切换到Turbo C窗口中。
　　
　　本软件在运行时并不需要UCDOS的支持，可以直接显示汉字，若您想要打入汉字，则需要启动UCDOS。

    软件启动时会自动检测有无题库，若未找到题库，则启动安装向导提示您安装。您还可以创建自己的题库，老师们如果有时间，也可以根据每年的教育部考试中心编写的二级考试习题集，来创建题库，以供同学们的每年的二级考试模拟练习使用。也可以在平时教学过程当中，利用该软件进行教学演示。
　
　　请随时关注Email: Skyever_youer@sohu.com，查询有本软件的升级信息。