
    如果您仅仅为了考试模拟使用，则本软件清楚直观的界面让您一目了然，不需要做太多的介绍。您甚至不用打开菜单，仅仅利用桌面上提供的按钮即可满足您的需要了。
 
    首先，每一个试题组都有改错题和编程题两种类型，您可以从“测试”中选择。选好以后，利用右上角的下拉列表便可以进行选择某套试题了。

    系统将会自动保留您所做的试题状态，在下次打开时，如果系统发现这题以前做过了，便询问是否将其初始化。初始化后的试题便为一道空题了，您也可以用右下角的“初始化”按钮进行初始化。

    打开试题后，系统首先显示题目内容，您可以点下面的“编辑”按钮来做题。如果做题有障碍的话，您可以点击“分析”按钮来看其对该题的分析。如果实在做不出来，您可以选择“答案”中的“填入参考答案”，参考答案将会填到您的编辑区域中了。

    完成后，您可以点击右下角的“编译”进行编译，如果有错的话，系统将在“编译”窗口中显示出来一系列的单选框，点击后将进行“编辑”窗口，并且光标将会停留在出错行上了。编译无误后，请点击“运行”按钮，窗口将切换到DOS状态下，出现您运行的结果。

    如果您实在不习惯于这种编辑方式，您可以点击下面的“Turbo C”按钮，系统将把窗口切换到标准的Turbo C 2.0方式，在这里，您可以用其进行编辑和运行了。

    更详细的情况请仔细阅读帮助系统。