
    敬爱的老师，亲爱的同学们，祝您在新的一学期中有更好的发展。

    “海阔天空”NCR2计算机等级考试(二级C语言)由［济南大学材料系学办］负责开发。作为新学期的献礼，献给：

	辛勤工作着的园丁们
	即将参加二级考试的广大热爱生活的同学们
	各位志同道合的朋友们

    希望你们人生的路途越来越宽阔，前进的脚步越来越快捷……


    该软件的版权属于广大老师和同学们，您可以自由拷贝，希望你们能够好好地利用该软件。老师们如果有时间，可以根据计算机等级考试中心每年出的《上机考试习题集》，来编写试题，以供同学们每年的等级考试使用。本软件提供了全功能的试题编写方法。

    在该软件随带的试题安装盘中，笔者对今年教育部考试中心提供的二百余题习题，提供了详细的答案及帮助说明，希望对您的二级考试大有帮助。

    老师们还可以利用该软件进行教学演示，该软件提供了多个窗口转换的功能，其中有试题说明窗口、编辑窗口、答案说明窗口、编辑窗口、运行窗口，并且附带着方便的Turbo C 2.0窗口的随时切换，当退出Turboc C 2.0窗口时又回到本软件中。
 
    如果您仅仅为了考试模拟使用，则本软件清楚直观的界面让您一目了然，不需要做太多的介绍。您甚至不用打开菜单，仅仅利用桌面上提供的按钮即可满足您的需要了。

    本软件的功能较多，不作详细的介绍。有关更详细的资料可以查看帮助系统用软件使用说明书。

    本软件的安装方法为：将安装盘插入软驱中，直接双击Install.exe即可在桌面上或者在C盘的根目录下展开为一个文件夹Ncr2。然后您再将其移动到您想要的地方。

    软件运行时会自动搜索试题，软件安装盘中未带试题，当软件提示安装试题时，请将试题安装盘插入软驱中，按照软件的提示选择A盘下的2002.EXM文件，点击确定，试题便开始安装了。安装完毕后软件提示是否将其转化为当前试题，选“是”就行了。

    请随时关注Email:Skyever_youer@sohu.com查询有无本软件的升级信息，及新试题信息。  
    
