A#include <stdio.h>
A#define N 8
Atypedef  struct
A { char num[10];
A   double s;
A } STREC;
A
Adouble fun(STREC *a, STREC *b, int *n)
A {
H   double sum = 0.0, ave;
H   int k; *n=0;
H   for(k=0; k<N; k++)   sum += a[k].s;
H   ave = sum/N;
H   for(k=0; k<N; k++)
H     if(a[k].s<ave)
H       b[(*n)++] = a[k];
H   return ave;
A }
A
Amain()
A { STREC s[N] = {{"GA05",85}, {"GA03",76}, {"GA02",69}, {"GA04",85},
A                 {"GA01",91}, {"GA07",72}, {"GA08",64}, {"GA06",87}
A                };
A   STREC h[N], t;
A   int i, j, n;  double ave;
A   ave = fun(s, h, &n);
A   printf("The %d student data which is lower than %7.3f:\n", n, ave);
A   for(i=0; i<n; i++)
A     printf("%s  %4.1f\n", h[i].num, h[i].s);
A   printf("\n");
A }
