
    这个程序要求找出低于平均分的项来，然后我们在开始并不知道平均分，所以第一
步自然就是求平均分了。

    在这里要求建立一个循环，并且定义一个变量来求和，在开始不要忘了把这个变量
赋为零值。循环完后，在这个变量中的数就是和了，于是平均分也就得出来了。

    再一个提醒您在开始不要忘了把*n也赋为零，且在用的过程中要自增，即(*n)++；
注意不要写成*n++，这样就变成了地址的自增了。

    在函数结束前不要忘了有返回值，否则在运行的时候将会出现致命的浮点错误。


