
    下列给定程序中，函数fun的功能是：求Ｓ的值。设

    Ｓ = (1*1)/(1*3) * (4*4)/(3*5) * ... * (2k*2k)/((2k-1)*(2k-1))

    例如，当k为10时，函数值应为1.533852。

    请改正程序中的错误，使程序能输出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
