
    下列给定程序中，函数fun的功能是：利用插入排序法对字符串中的字符按从小到大
的顺序进行排序。插入法的基本算法是：先对字符串中的头两个元素进行排序。然后把
第三个字符插入到前两个字符中，插入后前三个字符依然有序：再把第四个字符插入到
前三个字符中，......  待排序的字符串也在主函数中赋予。

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行或删行，也不得更改程序的结构！
