
    下列给定程序中，函数fun的功能是：给一维数组a输入任意４个整数，并按如下的
规律输出。例如输入１、２、３、４，程序运行后将输出以下方阵。

    ４ １ ２ ３
    ３ ４ １ ２
    ２ ３ ４ １
    １ ２ ３ ４

    请改正程序中的错误，使它能得出正确的结果。

    注意：不要改动main函数，不得增行删行，也不得更改程序的结构！
